name: actions

on:
  pull_request:
    types:
      - closed

jobs:
  build-push-image:
    if: ${{ github.ref == 'refs/heads/main' }}  # 检测main分支是否有更新
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # pull代码到运行服务器上
      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: "${{ secrets.REGISTRY_USERNAME }}" # 引用GitHub repo设置的镜像容器服务用户名
          password: "${{ secrets.REGISTRY_PASSWORD }}" # 引用GitHub repo设置的镜像容器服务密码
      - name: Build and Push Docker Image
        if: github.event.pull_request.merged == true
        run: |
          echo "start image build and push" 
          
          repo_name=`echo ${{ github.repository }} | awk -F "/" '{print $2}'`
          
          PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
          
          FILES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files" \
            | jq -r '.[].filename')
          
          filtered_folders=$(printf "%s\n" "${FILES[@]}" | grep -o '^minecraft-server-[^/]*' | sort | uniq)
          
          echo "Filtered folders: $filtered_folders"
          
          for folder in $filtered_folders; do
            tag="${folder#minecraft-server-}"
            echo "building minecraft-server::$tag"
            docker buildx build --platform=linux/amd64 -t ceerdecy/minecraft-server:"$tag" ./"$folder"
            echo "pushing minecraft-server::$tag"
            docker push ceerdecy/minecraft-server:"$tag"
          done